# Generated by Django 5.2 on 2025-04-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azfi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beforeafterimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='beforeafterimage',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beforeafterimage',
            name='sessions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
